name: CI
env:
  GO_VERSION: 1.25.0
  PYTHONPATH: /tmp/instr
  BASH_ENV: /tmp/instr/bash_env.sh
jobs:
  golang-lint:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Golang
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}
    - name: Run go fmt test
      run: hack/verify-gofmt.sh
      env:
        GO111MODULE: auto
    - name: Build the pixiu binariy
      run: go build -v ./...
    - name: Run pixiu unit test
      run: go test -v ./...
    timeout-minutes: 6
'on':
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
